const assert=require('node:assert/strict'),rt=require('./runtime.cjs')();rt.sandbox.assert=assert;
rt.run(`
function encounter(m='story'){mode=m;stage=3;score=0;loadStage();state='playing';checkpoint=storyStretchX(2820);boss.active=true;bossAnnounced=true;dialogueSeen=new Set(Object.keys(conversations));nessie={x:storyStretchX(2900),y:370,vx:0,vy:0,face:1};invincible=1000;}
function bossTicks(sec){for(let i=0;i<Math.ceil(sec*60);i++){updateRana(1/60);}}
function opening(){nessie.x=storyStretchX(2900);nessie.y=370;for(let i=0;i<2400&&rana.state!=='vulnerable';i++)updateRana(1/60);assert.equal(rana.state,'vulnerable','Choreography always leads to an opening');}
function hit(){opening();nessie.x=boss.x;nessie.y=boss.y;dashTime=.3;boss.hitCooldown=0;updateRana(.016);}
// Six genuine vulnerable contacts; phases, transitions and escapes are driven by actual damage.
encounter();assert.equal(boss.hp,6);const phases=[],visited=new Set();for(let n=0;n<6;n++){opening();visited.add(rana.state);const before=boss.hp;nessie.x=boss.x;nessie.y=boss.y;dashTime=.3;boss.hitCooldown=0;updateRana(.016);assert.equal(boss.hp,before-1);assert(bossLeapReady);assert(rana.hitStop>0);phases.push(rana.phase);if(n<5){assert.equal(rana.state,'stagger');bossTicks(.8);if(n===1||n===3){assert.equal(rana.state,'phaseTransition');bossTicks(1.6);}assert.equal(rana.state,'retaliationCharge');assert(rana.beams.length===0||rana.beams.every(b=>b.width===14));bossTicks(.2);assert(!boss.laserActive);bossTicks(2);assert.equal(rana.state,'retaliation');assert(boss.laserActive);bossTicks(2.4);assert.equal(rana.state,'observe');}}
assert.deepEqual(phases,[1,2,2,3,3,3]);assert.equal(boss.hp,0);assert.equal(rana.state,'defeated');assert(!rana.victoryReady);nessie.x=storyStretchX(3630);nessie.y=540;updateStory(.016);assert.equal(state,'playing','Portal stays sealed during defeat');bossTicks(4.1);assert(rana.victoryReady);assert.equal(score,450*6+1800);assert.equal(enemies.filter(isReefShark).length,6);assert(enemies.filter(isReefShark).every(e=>e.maxHp===4));updateStory(.016);assert.equal(state,'playing','Expanded hunt still requires the far portal');nessie.x=W-170;nessie.y=540;updateStory(.016);assert.equal(state,'finished','Only manual far-portal entry completes the game');
// Each phase runs all its attack families with bounded arrays and opportunities to dodge.
const seen=new Set();for(let phase=1;phase<=3;phase++){encounter();rana.phase=phase;boss.hp=phase===1?6:phase===2?4:2;for(let i=0;i<18000;i++){nessie.x=storyStretchX(2860);nessie.y=370;updateRana(1/60);seen.add(rana.state);assert(projectiles.length<=64);assert(finalHazards.length<=12);assert(particles.length<=260);assert(rana.history.length<=7);assert(rana.trails.length<=16);for(const b of rana.beams){assert(Number.isFinite(b.x1+b.x2+b.y1+b.y2));}if(rana.state==='vulnerable')assert(finalHazards.length===0&&rana.rings.length===0);}}
for(const s of ['laserCharge','laserSweep','acidCharge','acidVolley','jungleCommand','commandStrike','lungePrepare','lunge','croakCharge','shockwave','seedOrbit','tongueSnap','bellyFlop','discoSweep'])assert(seen.has(s),'State exercised: '+s);
// Guarded body contact hurts; boost only removes HP in the green window.
encounter();invincible=0;nessie.x=boss.x;nessie.y=boss.y;dashTime=.3;updateRana(.016);assert.equal(boss.hp,6);assert.equal(health,4);ranaNext('vulnerable');boss.hitCooldown=0;invincible=0;dashTime=0;updateRana(.016);assert.equal(boss.hp,6);dashTime=.3;updateRana(.016);assert.equal(boss.hp,5);assert(bossLeapReady);
// Earned double flip consumes one charge and crosses exactly two launch zones.
keys.add('ArrowUp');requestJump();keys.clear();assert(leap.active);assert.equal(leap.variant,'boss');assert(!bossLeapReady);const target=leap.target;invincible=1000;for(let i=0;i<500&&leap.active;i++)update(1/60);assert(!leap.active);assert(Math.abs(nessie.x-target)<75);
// Shared warning geometry is non-damaging until the attack begins. Laser target never tracks.
encounter();invincible=0;ranaNext('laserCharge');const locked={...rana.target};nessie.x+=180;nessie.y+=120;updateRana(.1);assert.deepEqual(rana.target,locked);assert.equal(health,5);ranaNext('laserSweep');rana.beams=ranaBeamGeometry(.3,true);const beam=rana.beams[0];nessie.x=(beam.x1+beam.x2)/2;nessie.y=(beam.y1+beam.y2)/2;assert(ranaSegmentDistance(nessie.x,nessie.y,beam.x1,beam.y1,beam.x2,beam.y2)<.001);rana.time=.3*RANA_TIMES.laserSweep;updateRana(.001);assert.equal(health,4,'Active beam collision');
// A travelling ring has a real safe gap, an empty centre and a damaging annulus.
encounter();rana.rings=[];ranaRing(3100,600,Math.PI,.72,310);invincible=0;nessie.x=3035;nessie.y=600;updateRanaEffects(.001);assert.equal(health,5);nessie.x=3100;nessie.y=600;updateRanaEffects(.001);assert.equal(health,5);nessie.x=3166;nessie.y=600;updateRanaEffects(.001);assert.equal(health,4);
// Hazards warn first. Vine, cloud and geyser collide with their drawn shapes.
for(const kind of ['vine','spore','geyser']){encounter();invincible=0;ranaHazard(kind,3000,kind==='spore'?600:865,.5);nessie.x=3000;nessie.y=kind==='spore'?600:700;updateRanaHazards(.1);assert.equal(health,5);updateRanaHazards(1);assert.equal(health,4,kind+' collision');}
// Projectiles, finite homing, underwater immunity and existing resources.
encounter();invincible=0;projectiles=[{x:nessie.x,y:nessie.y,vx:0,vy:0,life:2,type:'acid',hitRadius:30}];updateStory(.016);assert.equal(health,4);collectPowerup({type:'heart',x:nessie.x,y:nessie.y});assert.equal(health,5);assert(heartJumpTime>0);collectPowerup({type:'boost',x:nessie.x,y:nessie.y});assert(boostUnlimited>0);projectiles=[{x:3000,y:500,vx:-200,vy:0,life:2,type:'acid',ranaOwned:true,variant:'homing',age:.9}];updateStory(.016);assert.equal(projectiles[0].variant,'straight');
// Death/checkpoint retry clears attack, charge, phase, particles and motion state.
encounter();checkpoint=storyStretchX(2820);health=1;invincible=0;hurt(nessie.x);assert.equal(state,'finished');rana.phase=3;ranaNext('discoSweep');rana.rings.push({r:100});bossLeapReady=true;retryStory();assert.equal(state,'playing');assert.equal(boss.hp,6);assert.equal(rana.phase,1);assert.equal(rana.state,'observe');assert.equal(rana.rings.length,0);assert.equal(rana.beams.length,0);assert.equal(finalHazards.length,0);assert(!bossLeapReady);assert.equal(particles.length,0);assert.equal(popups.length,0);assert.equal(nessie.x,storyStretchX(2820));
// Victory dialogue is deferred until the defeat animation finishes; dialogue then portal then ending.
encounter('sarah');dialogueSeen.delete('final-boss-win');dialogueSeen.delete('final');boss.hp=1;ranaNext('vulnerable');nessie.x=boss.x;nessie.y=boss.y;dashTime=.3;updateRana(.016);assert.equal(state,'playing');bossTicks(4);assert.equal(state,'dialogue');assert(dialogueSeen.has('final-boss-win'));finishDialogue();assert(isNessieFinal());assert.equal(nessieTwist.phase,'arrival');assert(!familyPortalOpen());
console.log('Rana encounter passed: six hits, all three phases, every attack family, warnings, collisions, pickups, double flip, retry, defeat dialogue, portal and ending.');
`);
