const fs=require('node:fs'),path=require('node:path'),{createCanvas,loadImage}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/@napi-rs/canvas');
async function render(){const names=['highlands','colombia','nessie','dancers','barrier-reef','barrier-jungle','flora-layer','carlo','miguel','rana-rex','sarah-mermaid','dialogue-friends','king-daddy-atlas','queen-antonella-atlas','pearl-palace','training-lagoon','environment-atlas','creature-atlas','tutorial-magic-atlas','gentleman-shark','tutorial-reef-v6','tutorial-daddy-faces-v6','boss-wild-parts','boss-sea-parts','boss-royal-parts','boss-spell-parts'];const images=await Promise.all(names.map(name=>loadImage(path.resolve(__dirname,'../dist/assets/'+name+'.webp'))));for(const img of images){Object.defineProperties(img,{src:{set(){}},naturalWidth:{get(){return this.width}},naturalHeight:{get(){return this.height}},complete:{get(){return true}}});img.addEventListener=()=>{};}const rt=require('./runtime.cjs')(true,images);
const out=process.argv[2]||'/tmp/rana-contact-sheet.png',sheet=createCanvas(2100,1440),sc=sheet.getContext('2d');
const states=[['King of the Ruin','observe',1,6,.4],['Locked laser warning','laserCharge',1,6,.8],['Laser sweep','laserSweep',1,6,.7],['Living jungle','jungleCommand',2,4,.9],['Tongue snap','tongueSnap',2,4,.18],['Green opening','vulnerable',2,3,1],['Laser Disco of Doom','discoSweep',3,2,1.1],['Double-flip retaliation','retaliationCharge',3,1,1.3],['Party restored','defeated',3,0,4.1]];
for(const [i,[label,state,phase,hp,time]] of states.entries()){rt.run(`mode='sarah';stage=3;loadStage();state='playing';camera=2400;boss.active=true;bossAnnounced=true;boss.hp=${hp};rana.phase=${phase};nessie.x=2920;nessie.y=500;dialogueSeen=new Set(Object.keys(conversations));ranaNext('${state}');rana.time=${time};rana.total=20;invincible=1000;${state==='defeated'?'rana.victoryReady=true;rana.defeatTime=4.1;':''}updateRana(.001);draw(20);`);sc.drawImage(rt.surface,i%3*700,Math.floor(i/3)*480,700,480);sc.fillStyle='#102534ed';sc.fillRect(i%3*700,Math.floor(i/3)*480,700,28);sc.fillStyle='#e1fff1';sc.font='bold 16px sans-serif';sc.fillText(label,i%3*700+12,Math.floor(i/3)*480+20);}
fs.writeFileSync(out,sheet.toBuffer('image/png'));console.log(out);

}
render().catch(e=>{console.error(e);process.exit(1)});
