const fs=require('node:fs'),path=require('node:path'),{createCanvas,loadImage}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/@napi-rs/canvas');
async function render(){const names=['highlands','colombia','nessie','dancers','barrier-reef','barrier-jungle','flora-layer','carlo','miguel','rana-rex','sarah-mermaid','dialogue-friends','king-daddy-atlas','queen-antonella-atlas','pearl-palace','training-lagoon','environment-atlas','creature-atlas','tutorial-magic-atlas','gentleman-shark','tutorial-reef-v6','tutorial-daddy-faces-v6','boss-wild-parts','boss-sea-parts','boss-royal-parts','boss-spell-parts'];const images=await Promise.all(names.map(name=>loadImage(path.resolve(__dirname,'../dist/assets/'+name+'.webp'))));for(const img of images){Object.defineProperties(img,{src:{set(){}},naturalWidth:{get(){return this.width}},naturalHeight:{get(){return this.height}},complete:{get(){return true}}});img.addEventListener=()=>{};}const rt=require('./runtime.cjs')(true,images);
const out=process.argv[2]||'/tmp/rana-contact-sheet.png',sheet=createCanvas(2100,1440),sc=sheet.getContext('2d');
const states=[['Training lagoon',-1,0,'idle',.4],['Elite rock',-1,950,'idle',1],['King Daddy’s test',-1,2400,'boss',1],['Royal Gardens',2,200,'idle',1],['Pearl Galleries',2,1200,'idle',1],['Grand Court entrance',2,2400,'observe',.4],['Crown warning',2,2400,'crownCharge',.8],['Whirlpool ballet',2,2400,'whirl',1.2],['Royal approval',2,2400,'defeated',3.8]];
for(const [i,[label,chapter,cam,pose,time]] of states.entries()){rt.run(`mode='sarah';stage=${chapter};loadStage();state='playing';camera=${cam};nessie.x=${cam+520};nessie.y=500;dialogueSeen=new Set(Object.keys(conversations));invincible=1000;${chapter===-1?pose==='boss'?"training.step=6;training.bossEntry=3;boss.active=true;boss.clock=7;boss.vulnerable=true;":"training.step=1;":"boss.active="+(cam>2000)+";queen.entry=4;queen.phase=3;queenNext('"+pose+"');queen.time="+time+";"+(pose==='defeated'?"boss.hp=0;queen.victoryReady=true;queen.crown=3.8;":"")}draw(20);`);sc.drawImage(rt.surface,i%3*700,Math.floor(i/3)*480,700,480);sc.fillStyle='#102534ed';sc.fillRect(i%3*700,Math.floor(i/3)*480,700,28);sc.fillStyle='#e1fff1';sc.font='bold 16px sans-serif';sc.fillText(label,i%3*700+12,Math.floor(i/3)*480+20);}
fs.writeFileSync(out,sheet.toBuffer('image/png'));console.log(out);

}
render().catch(e=>{console.error(e);process.exit(1)});
