const fs=require('node:fs'),path=require('node:path'),{createCanvas,loadImage}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/@napi-rs/canvas');
async function render(){const names=['highlands','colombia','nessie','dancers','barrier-reef','barrier-jungle','flora-layer','carlo','miguel','rana-rex','sarah-mermaid','dialogue-friends','king-daddy-atlas','queen-antonella-atlas','pearl-palace','training-lagoon','environment-atlas','creature-atlas','tutorial-magic-atlas','gentleman-shark','tutorial-reef-v6','tutorial-daddy-faces-v6','boss-wild-parts','boss-sea-parts','boss-royal-parts','boss-spell-parts'];const images=await Promise.all(names.map(name=>loadImage(path.resolve(__dirname,'../dist/assets/'+name+'.webp'))));for(const img of images){Object.defineProperties(img,{src:{set(){}},naturalWidth:{get(){return this.width}},naturalHeight:{get(){return this.height}},complete:{get(){return true}}});img.addEventListener=()=>{};}const rt=require('./runtime.cjs')(true,images);
const out=process.argv[2]||'/tmp/rana-contact-sheet.png',sheet=createCanvas(2100,960),sc=sheet.getContext('2d');
const states=[['A very normal quest',0,''],['Nessie returns',3,"beginNessieFinal();boss.x=3280;"],['The crown awakens',3,"beginNessieFinal();boss.x=3280;nessieNext('transform');nessieTwist.time=1.6;"],['A royal warning',3,"beginNessieFinal();boss.x=3280;boss.active=true;nessieNext('charge');nessieTwist.attack='rush';"],['Crown wave · safe gap',3,"beginNessieFinal();boss.x=3280;boss.active=true;nessieNext('wave');updateNessieFinal(.5);nessieTwist.rings[0].r=350;"],['Boost into the opening',3,"beginNessieFinal();boss.x=3280;boss.active=true;nessieNext('open');"]];
for(const [i,[label,chapter,code]] of states.entries()){rt.run(`mode='sarah';stage=${chapter};loadStage();state='playing';dialogueSeen=new Set();nessie.x=${chapter?2920:350};nessie.y=600;${code}camera=nessie.x-vw*.43;draw(20);`);sc.drawImage(rt.surface,i%3*700,Math.floor(i/3)*480,700,480);sc.fillStyle='#102534ed';sc.fillRect(i%3*700,Math.floor(i/3)*480,700,28);sc.fillStyle='#e1fff1';sc.font='bold 16px sans-serif';sc.fillText(label,i%3*700+12,Math.floor(i/3)*480+20);}
fs.writeFileSync(out,sheet.toBuffer('image/png'));console.log(out);

}
render().catch(e=>{console.error(e);process.exit(1)});
