'use strict';
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const elements=new Map(),noop=()=>{};
const context=new Proxy({createLinearGradient:()=>({addColorStop:noop}),createRadialGradient:()=>({addColorStop:noop})},{get:(o,k)=>o[k]||noop,set:(o,k,v)=>(o[k]=v,true)});
function el(id){if(elements.has(id))return elements.get(id);const e={style:{setProperty:noop},dataset:{},children:[],classList:{toggle:noop,add:noop,remove:noop},textContent:'',innerHTML:'',parentElement:{style:{}},setAttribute:noop,focus:noop,appendChild(c){this.children.push(c)},addEventListener:noop,querySelector:()=>null,querySelectorAll:()=>[],getBoundingClientRect:()=>({width:1400,height:960}),getContext:()=>context};elements.set(id,e);return e;}
const sandbox={assert,console,Math,Set,Image:class{complete=true;naturalWidth=1536;naturalHeight=1024;addEventListener(){}},document:{getElementById:el,querySelector:el,querySelectorAll:()=>[],addEventListener:noop,createElement:el},window:{matchMedia:()=>({matches:false}),addEventListener:noop},localStorage:{getItem:()=>null,setItem:noop},ResizeObserver:class{constructor(fn){this.fn=fn}observe(){this.fn()}},devicePixelRatio:1,performance:{now:()=>0},requestAnimationFrame:noop,setTimeout:noop};
vm.createContext(sandbox);vm.runInContext(fs.readFileSync(path.join(__dirname,'../dist/polish.js'),'utf8'),sandbox);vm.runInContext(fs.readFileSync(path.join(__dirname,'../dist/music.js'),'utf8'),sandbox);vm.runInContext(fs.readFileSync(path.join(__dirname,'../dist/family.js'),'utf8'),sandbox);vm.runInContext(fs.readFileSync(path.join(__dirname,'../dist/rana.js'),'utf8'),sandbox);vm.runInContext(fs.readFileSync(path.join(__dirname,'../dist/conversation.js'),'utf8'),sandbox);vm.runInContext(fs.readFileSync(path.join(__dirname,'../dist/game.js'),'utf8'),sandbox);
vm.runInContext(`
function beginJumpTest(nextStage=0,nextMode='story'){mode=nextMode;stage=nextStage;score=0;loadStage();state='playing';dialogueSeen=new Set(Object.keys(conversations));bossAnnounced=true;}
function stepSeconds(seconds,rate=60){for(let i=0;i<Math.ceil(seconds*rate);i++)update(1/rate);}
// Every chapter and both heroes share the launch mechanic; Time Trial keeps its required coin count.
for(const m of ['story','sarah','trial'])for(let chapter=0;chapter<4;chapter++){beginJumpTest(chapter,m);assert.equal(launchPads.length,4);assert.equal(collected(),0);assert.equal(coins.filter(c=>c.type==='coin').length,stages[stage].count);assert.equal(powerups.filter(p=>p.sky&&p.type==='boost').length,4);assert.equal(powerups.filter(p=>p.sky&&p.type==='heart').length,m==='trial'?0:4);}
// Up + Boost launches away from rings; depleted boost must recharge before another launch.
beginJumpTest();nessie.x=220;nessie.y=waterSurface()+25;keys.add('ArrowUp');burst();assert(leap.active);stepSeconds(2.5);assert.equal(leap.active,false);assert(nessie.y>=waterSurface()+25);keys.clear();beginJumpTest();const first=launchPads[0];nessie.x=first.x;nessie.y=first.y;energy=.05;dashCooldown=0;burst();assert.equal(leap.active,false);stepSeconds(.6);assert(energy>=.4);dashCooldown=0;
// A real launch leaves the surface, collects both sky rewards, then returns to swimming.
enemies=[];projectiles=[];health=4;burst();assert.equal(leap.active,true);assert(nessie.vy<0);const airPath=[];for(let i=0;i<120;i++){update(1/60);airPath.push([nessie.x,nessie.y,leap.active]);}assert(Math.min(...airPath.map(p=>p[1]))<waterSurface()-140);assert(Math.min(...airPath.map(p=>p[1]))>=85);assert.equal(leap.active,false);assert.equal(health,5);assert(boostUnlimited>0);assert(powerups.filter(p=>p.sky&&p.taken).length>=2);assert(surfaceRipples.length>0);assert(nessie.y>=waterSurface()+25);
// Underwater attacks cannot follow the hero above the water; normal damage resumes after splashdown.
beginJumpTest(2);nessie.x=3030;nessie.y=waterSurface()-90;leap.active=true;leap.breached=true;health=4;invincible=0;hurt(nessie.x);assert.equal(health,4);projectiles=[{x:nessie.x,y:waterSurface()-80,vx:0,vy:0,life:3,type:'acid',variant:'straight'}];updateStory(.016);assert.equal(projectiles.length,0);assert.equal(health,4);landLeap();assert(invincible>0);invincible=0;hurt(nessie.x);assert.equal(health,3);
// Unlimited boost cannot overwrite gravity in the air, even while the button is held.
beginJumpTest();nessie.x=first.x;nessie.y=first.y;boostUnlimited=8;keys.add(' ');burst();const velocity=nessie.vy;burst();assert.equal(nessie.vy,velocity);stepSeconds(2);assert.equal(leap.active,false);assert(nessie.y>=waterSurface()+25);keys.clear();
// Down + Boost stays underwater. Down during flight returns sooner than a normal arc.
beginJumpTest();nessie.x=first.x;nessie.y=first.y;keys.add('ArrowDown');burst();assert.equal(leap.active,false);assert(nessie.vy>0);keys.clear();
function flightTime(dive,rate=60){beginJumpTest(0,'trial');nessie.x=540;nessie.y=launchPads[0].y;burst();if(dive)keys.add('ArrowDown');let ticks=0;while(leap.active&&ticks<300){update(1/rate);ticks++;}keys.clear();assert.equal(leap.active,false);return ticks/rate;}
const normal=flightTime(false),quick=flightTime(true);assert(quick<normal-.15);assert(Math.abs(flightTime(false,30)-flightTime(false,120))<.06);
// Reverse launches skim the reef rather than teleporting through it or getting stuck on it.
beginJumpTest();nessie.x=1450;nessie.y=launchPads[1].y;keys.add('ArrowLeft');burst();let biggestStep=0,prior=nessie.x;for(let i=0;i<210&&leap.active;i++){update(1/60);biggestStep=Math.max(biggestStep,Math.abs(nessie.x-prior));prior=nessie.x;}keys.clear();assert.equal(leap.active,false);assert(biggestStep<25);assert(nessie.y>=waterSurface()+25);
// Launches across the entire ring remain continuous, including reverse reef crossings.
for(const m of ['story','sarah','trial'])for(let chapter=0;chapter<4;chapter++)for(let ring=0;ring<4;ring++)for(const dir of [-1,1])for(const offset of [-60,0,60]){beginJumpTest(chapter,m);enemies=[];boss=null;finalHazards=[];nessie.x=launchPads[ring].x+offset;nessie.y=launchPads[ring].y+20;nessie.face=dir;burst();assert(leap.active);let previousX=nessie.x,ticks=0,breached=false;while(leap.active&&ticks++<360){update(1/60);breached ||= leap.breached;assert(Math.abs(nessie.x-previousX)<20,'No teleport at splashdown');previousX=nessie.x;}assert(breached,'Every valid launch clears the water');assert.equal(leap.active,false,'Every launch returns to swimming');}
// Pausing freezes flight; chapter loads and checkpoint retries clear flight state.
beginJumpTest();nessie.x=540;nessie.y=launchPads[0].y;burst();state='paused';const frozen=[nessie.x,nessie.y,leap.time];stepSeconds(.5);assert.deepEqual([nessie.x,nessie.y,leap.time],frozen);state='playing';retryStory();assert.equal(leap.active,false);assert.equal(leap.cooldown,0);assert.equal(surfaceRipples.length,0);stage=1;loadStage();assert.equal(leap.active,false);assert(launchPads.every(p=>p.y===waterSurface()+75));
// The combat cue teaches Carlo once, stays brief, and never pauses gameplay.
bossLessonSeen=false;bossLessonTime=0;beginJumpTest(0,'story');nessie.x=3030;nessie.y=430;checkpoint=2820;enemies=[];boss.active=true;boss.clock=4.6;boss.vulnerable=true;hud();assert.equal(state,'playing');assert(bossLessonSeen);assert.equal($('boss-lesson').style.display,'flex');assert.equal($('boss-cue').dataset.cue,'boost');assert.equal($('coin-progress').dataset.cue,'compass');const remainingLesson=bossLessonTime;stepSeconds(.5);assert(bossLessonTime<remainingLesson);pause();assert.equal($('boss-lesson').style.display,'none');const pausedLesson=bossLessonTime;stepSeconds(.5);assert.equal(bossLessonTime,pausedLesson);retryStory();assert.equal(bossLessonTime,0);boss.active=true;boss.vulnerable=true;hud();assert.equal($('boss-lesson').style.display,'none');beginJumpTest(1,'story');boss.active=true;boss.vulnerable=true;hud();assert.equal($('boss-lesson').style.display,'none');boss.vulnerable=false;hud();assert.equal($('boss-cue').dataset.cue,'shield');boss.hp=0;hud();assert.equal($('coin-progress').dataset.cue,'portal');
// World actions use compact icons while launch, pickups and combat avoid instruction toasts.
beginJumpTest();nessie.x=540;nessie.y=launchPads[0].y;hud();assert.equal($('boost-icon').dataset.cue,'leap');const beforeToast=$('toast').textContent;burst();assert.equal($('toast').textContent,beforeToast);collectPowerup({x:700,y:200,type:'boost',taken:false});assert.equal($('toast').textContent,beforeToast);
// The full vertical column accepts a straight-up launch from deep water in every chapter.
for(let chapter=0;chapter<4;chapter++)for(const depth of [500,760,870]){beginJumpTest(chapter);enemies=[];boss=null;finalHazards=[];nessie.x=launchPads[0].x;nessie.y=depth;assert(nearLaunchPad());keys.add('ArrowUp');burst();keys.clear();const startX=nessie.x;let breached=false,ticks=0;while(leap.active&&ticks++<300){const wasAir=leap.breached;update(1/60);if(!wasAir&&!leap.breached)assert.equal(nessie.x,startX);breached ||= leap.breached;}assert(breached);assert.equal(leap.active,false);}
// A dive started below the surface cancels safely rather than trapping the swimmer in flight.
beginJumpTest();boss=null;enemies=[];nessie.x=540;nessie.y=870;burst();keys.add('ArrowDown');stepSeconds(3);keys.clear();assert.equal(leap.active,false);assert(nessie.y<=870);
// Each power-up combination chooses a stable animation for the whole jump.
for(const variant of ['standard','heart','boost','combo','boss']){beginJumpTest();boss=null;enemies=[];nessie.x=1450;nessie.y=500;if(variant==='heart'||variant==='combo')collectPowerup({x:1450,y:500,type:'heart'});if(variant==='boost'||variant==='combo')collectPowerup({x:1450,y:500,type:'boost'});if(variant==='boss')bossLeapReady=true;burst();assert.equal(leap.variant,variant);if(variant==='boss')assert.equal(bossLeapReady,false);leap.breached=true;leap.airTime=leap.airDuration*.5;const pose=jumpPose();assert(Number.isFinite(pose.angle));assert(pose.squash>=.6&&pose.squash<=1.1);leap.airTime=leap.airDuration;const landingPose=jumpPose();if(variant==='boss')assert(Math.abs(landingPose.angle-Math.PI*4)<.001);if(variant==='boost'||variant==='combo')assert(Math.abs(landingPose.angle-Math.PI*2)<.001);heartJumpTime=0;boostUnlimited=0;assert.equal(leap.variant,variant);}
// A real vulnerable boss hit earns exactly one stored leap, usable with Up + Boost away from a ring.
beginJumpTest();nessie.x=3280;nessie.y=705;checkpoint=2820;enemies=[];boss.active=true;boss.clock=4.6;boss.vulnerable=true;dashTime=.3;const hp=boss.hp;updateStory(.016);assert.equal(boss.hp,hp-1);assert(bossLeapReady);boss=null;dashCooldown=1;energy=0;keys.add('ArrowUp');burst();keys.clear();assert.equal(leap.variant,'boss');assert.equal(bossLeapReady,false);assert.equal(leap.target,1450);const target=leap.target;for(let i=0;i<300&&leap.active;i++)update(1/60);assert.equal(leap.active,false);assert(Math.abs(nessie.x-target)<55);assert.equal(bossLeapReady,false);
// Held unlimited boost cannot accidentally consume the earned special; normal attacks still work.
beginJumpTest();nessie.x=3280;nessie.y=500;bossLeapReady=true;boostUnlimited=8;keys.add('ArrowUp');burst(true);assert.equal(leap.active,false);assert(bossLeapReady);keys.clear();
// Two-zone trajectories remain inside every chapter, including both edge launch zones.
for(let chapter=0;chapter<4;chapter++)for(let ring=0;ring<4;ring++){beginJumpTest(chapter);boss=null;enemies=[];finalHazards=[];nessie.x=launchPads[ring].x;nessie.y=760;bossLeapReady=true;burst();const expected=leap.target;const indices=[ring,launchPads.findIndex(p=>p.x===expected)];assert.equal(Math.abs(indices[0]-indices[1]),2);let ticks=0;while(leap.active&&ticks++<360)update(1/60);assert.equal(leap.active,false);assert(Math.abs(nessie.x-expected)<75);assert(nessie.x>=90&&nessie.x<=W-90);assert.equal(bossLeapReady,false);}
console.log('Surface leap checks passed: all modes, all chapters, sky rewards, escape, steering, dive, recharge, pause and resets.');
`,sandbox);
